#!/usr/bin/env bash
here=$(dirname "$0")
cd "$here"
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
$(which luajit||which lua) app.lua ../Resources/assets/cd_catalog.xml
exit 0
